### ISSUE TITLE
Opening TeX doc inside emacs

### ISSUE THREAD

**Issue by DrWaleedAYousef** [ROCKTAKEY/lsp-latex#33]
Currently, in spacemacs I can hit M-m m h d, which runs the command TeX-doc that suggest opening the appropriate pdf help document. However, it opens it in an external viewer. Do you have any idea how to open it in emacs using pdf-tools (it seems to be a very elisp/emacs question).

**Comment by stewmehr** [comment]
Hi,

I do not use spacemacs but I stumbled upon your question when googling for an answer to the same problem. As `texdoc` is a standalone application its pdf viewer has to be configured in the appropriate settings file. To find out where that file is located type
```bash
texdoc -f
```
in a terminal. The output should look similar to this:
```
/usr/share/texmf/scripts/texdoc/texdoclib.tlu 3.3
Configuration file(s):
    active      /usr/share/texmf/texdoc/texdoc.cnf
Recommended file(s) for personal settings:
    /home/westerholt/texmf/texdoc/texdoc.cnf
```
I had to create the recommended file because it did not exist yet. Since I use emacs in daemon mode I added the line
```
viewer_pdf = emacsclient
```
You can also use `viewer_pdf = emacs` instead, but this will most likely open a new frame which is not what I wanted.

**Comment by ROCKTAKEY** [comment]
@DrWaleedAYousef Sorry for late reply. See below section on readme.
https://github.com/ROCKTAKEY/lsp-latex#pdf-tools-integration

**Comment by DrWaleedAYousef** [comment]
> @DrWaleedAYousef Sorry for late reply. See below section on readme. https://github.com/ROCKTAKEY/lsp-latex#pdf-tools-integration

Thanks for your reply. I have no problem with the forward search and going back and forth between the tex code and the pdf. I am asking about opening a help on tex library or module within emacs.

**Comment by ROCKTAKEY** [comment]
@DrWaleedAYousef I got it.
 As far as I saw `TeX-documentation-texdoc` definition [here](https://github.com/emacsmirror/auctex/blob/b36127cc74808690cc042eac73952e3e75493d90/tex.el#L6331-L6414), there is no option to specify viewer.
So I think texdoc setting is needed as @hwesterholt said. Or you can request it to [AUCTeX](https://savannah.gnu.org/projects/auctex).
